# Requried variables:
#plant_name
#plant_num
#watering_gpio
#watering_time
#moisture_sensor_gpio

substitutions:
  min_water_time: "1"
  max_water_time: "3600"
  moisture_update_interval: 30s

defaults:
  plant_name: Plant $pwc_num-$plant_num

switch:
  - platform: gpio
    pin: 
      number: ${watering_gpio}
    name: ${plant_name} Watering
    id: p${plant_num}_relay
    icon: "mdi:water"
    on_turn_on:
    - logger.log: "${plant_name} Pump Turned On!"
    - delay: !lambda "return id(p${plant_num}_water_time).state * 1000;"
    - switch.turn_off: p${plant_num}_relay
    - logger.log: "${plant_name} Pump Turned Off!"

sensor:
  - platform: adc
    pin: ${moisture_sensor_gpio}
    name: ${plant_name} Moisture
    update_interval: ${moisture_update_interval}

# number:
#   - platform: template
#     name: "${plant_name} Watering Time"
#     id: p${plant_num}_water_time
#     icon: "mdi:timer"
#     entity_category: config
#     unit_of_measurement: "sec"
#     min_value: $min_water_time
#     max_value: $max_water_time
#     step: 1
#     optimistic: True
#     restore_value: True
#     initial_value: 60
    
sprinkler:
  - id: pwc
    valves:
      - valve_switch: "${plant_name}"
        enable_switch: "Enable ${plant_name}"
        run_duration_number: 
          name: "${plant_name} Watering Time"
          id: p${plant_num}_water_time
        valve_switch_id: p${plant_num}_relay
