# Requried variables:
#plant_name
#plant_num
#watering_gpio
#watering_time
#moisture_sensor_gpio

substitutions:
  min_water_time: "1"
  max_water_time: "3600"
  moisture_update_interval: 30s

defaults:
  plant_name: Plant $pwc_num-$plant_num


script:
  - id: water_plant_${plant_num}
    then:
      - switch.turn_on: p${plant_num}_watering
      - wait_until:
          condition:
            switch.is_off: p${plant_num}_watering
          timeout: "${max_water_time}s"
      - if:
          condition:
            switch.is_on: p${plant_num}_watering
          then:
            - logger.log: "PWC${pwc_num} Timeout Waiting for ${plant_name} to finish watering!"
            - switch.turn_off: p${plant_num}_watering

switch:
  - platform: gpio
    internal: True
    pin: 
      number: ${watering_gpio}
    id: p${plant_num}_relay
  - platform: template
    name: ${plant_name} Watering Enabled
    id: p${plant_num}_watering_enabled
    optimistic: True
    restore_mode: RESTORE_DEFAULT_ON
  - platform: template
    name: ${plant_name} Watering
    id: p${plant_num}_watering
    icon: "mdi:water"
    optimistic: True
    turn_on_action:
      - if:
          condition:
            switch.is_on: p${plant_num}_watering_enabled
          then:
            - logger.log: "${plant_name} Watering Starting"
            - switch.turn_on: p${plant_num}_relay
            - delay: !lambda "return id(p${plant_num}_water_time).state * 1000;"
            - switch.turn_off: p${plant_num}_relay
            - logger.log: "${plant_name} Watering Completed"
            - switch.turn_off: p${plant_num}_watering
          else:
            - logger.log: "${plant_name} watering requested, but is disabled. Ignoring."
            - switch.turn_off: p${plant_num}_relay
    turn_off_action:
      - switch.turn_off: p${plant_num}_relay
      - logger.log: "${plant_name} Watering Manually Stopped"

sensor:
  - platform: adc
    pin: ${moisture_sensor_gpio}
    name: ${plant_name} Moisture
    update_interval: ${moisture_update_interval}

number:
  - platform: template
    name: "${plant_name} Watering Time"
    id: p${plant_num}_water_time
    icon: "mdi:timer"
    entity_category: config
    unit_of_measurement: "sec"
    min_value: $min_water_time
    max_value: $max_water_time
    step: 1
    optimistic: True
    restore_value: True
    initial_value: 60
    