substitutions:
  pwc_num: "0"

  # Plant Names
  plant1: Plant $pwc_num-1
  plant2: Plant $pwc_num-2
  plant3: Plant $pwc_num-3
  plant4: Plant $pwc_num-4

  # Plant Watering Times
  p1_time: "1 min"
  p2_time: "1 min"
  p3_time: "1 min"
  p4_time: "1 min"

esphome:
  name: pwc$pwc_num
  friendly_name: Plant Watering Controller $pwc_num
  project:
    name: boozer2.Plant Watering Controller
    version: $version

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "PWC${pwc_num} Fallback Hotspot"
    password: "xvQA2w6dlf83"

packages:
  pwc: github://boozer2/pwc/pwc-main.yaml
