substitutions:
#  pwc_num: "0"

  # Plant Names
#  plant1_name: Plant $pwc_num-1
#  plant2_name: Plant $pwc_num-2
#  plant3_name: Plant $pwc_num-3
#  plant4_name: Plant $pwc_num-4

  name: "pwc${pwc_num}"
  friendly_name: "Plant Watering Controller ${pwc_num}"
  version: "0.6"
  
esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: false
  project:
    name: boozer2.pwc
    version: $version

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "PWC${pwc_num} Fallback Hotspot"
    password: "xvQA2w6dlf83"

captive_portal:
    
switch:
  - platform: gpio
    pin:
      number: GPIO23
    name: LED
    id: led

sensor:
  - platform: internal_temperature
    name: "Internal Temperature"
  - platform: uptime
    name: Uptime
  - platform: wifi_signal
    name: WiFi Signal dB

time:
  - platform: homeassistant
    id: homeassistant_time

packages:
  plant1: !include
      file: plant.yaml
      vars:
        plant_name: ${plant1_name}
        watering_gpio: GPIO32
        moisture_sensor_gpio: GPIO34
        plant_num: 1
  plant2: !include
      file: plant.yaml
      vars:
        plant_name: ${plant2_name}
        watering_gpio: GPIO33
        moisture_sensor_gpio: GPIO35
        plant_num: 2
  plant3: !include
      file: plant.yaml
      vars:
        plant_name: ${plant3_name}
        watering_gpio: GPIO25
        moisture_sensor_gpio: GPIO36
        plant_num: 3
  plant4: !include
      file: plant.yaml
      vars:
        plant_name: ${plant4_name}
        watering_gpio: GPIO26
        moisture_sensor_gpio: GPIO39        
        plant_num: 4

sprinkler:
  - id: lawn_sprinkler_ctrlr
    main_switch: "Lawn Sprinklers"
    auto_advance_switch: "Lawn Sprinklers Auto Advance"
    reverse_switch: "Lawn Sprinklers Reverse"
    multiplier_number: "Lawn Sprinkler Multiplier"
    repeat_number: "Lawn Sprinkler Repeat"
    # valve_overlap: 5s
    valves:
      - valve_switch: "Front Lawn"
        enable_switch: "Enable Front Lawn"
        run_duration_number: 
          name: "${plant1_name} Watering Time"
          id: p1_water_time
        valve_switch_id: p1_relay
      - valve_switch: "Side Lawn"
        enable_switch: "Enable Side Lawn"
        run_duration_number: "${plant2_name} Watering Time"
        valve_switch_id: p2_relay
      - valve_switch: "Back Lawn"
        enable_switch: "Enable Back Lawn"
        run_duration_number: "${plant3_name} Watering Time"
        valve_switch_id: p3_relay