substitutions:
  plant1: Plant 1
  plant2: Plant 2
  plant3: Plant 3
  plant4: Plant 4
    
  # Plant Watering Times
  p1_time: "1 min"
  p2_time: "1 min"
  p3_time: "1 min"
  p4_time: "1 min"
    
packages:
  pwc: !include pwc-main2.yaml

dashboard_import:
  package_import_url: github://boozer2/pwc/pwc-template.yaml
  import_full_config: false
