substitutions:
  # Plant Watering Controller Number
  pwc_num: "0"

  # Plant Names
  plant1_name: Plant $pwc_num-1
  plant2_name: Plant $pwc_num-2
  plant3_name: Plant $pwc_num-3
  plant4_name: Plant $pwc_num-4

packages:
  pwc: 
    url: https://github.com/boozer2/pwc
    ref: main
    file: pwc-main.yaml
    refresh: 1s
