substitutions:
  # Plant Watering Controller Number
  pwc_num: "99"
    
  # Plant Names
  plant1: Plant ${pwc_num}-1
  plant2: Plant ${pwc_num}-2
  plant3: Plant ${pwc_num}-3
  plant4: Plant ${pwc_num}-4
    
  # Plant Watering Times
  p1_time: "1 min"
  p2_time: "1 min"
  p3_time: "1 min"
  p4_time: "1 min"
    
packages:
  pwc: github://boozer2/pwc/pwc-main.yaml@main

dashboard_import:
  package_import_url: github://boozer2/pwc/pwc-template.yaml@main
  import_full_config: false
